apiVersion: v1
entries:
  ontop-endpoint:
  - apiVersion: v2
    appVersion: v2024.1.2
    created: "2024-06-18T16:33:23.045769632+02:00"
    description: A Helm chart for Kubernetes
    digest: ae0c710dd9258d1e9332bf091896283902d92b694088d41049f97cdc01b44208
    name: ontop-endpoint
    type: application
    urls:
    - https://ontopic-vkg.github.io/ontopic-helm/ontop-endpoint-0.1.0.tgz
    version: 0.1.0
  ontopic-studio:
  - apiVersion: v2
    appVersion: v2024.1.2
    created: "2024-06-18T16:33:23.04785373+02:00"
    description: A Helm chart for Kubernetes
    digest: c8f905b4ecad79d4be1341690bfe9be45f5e3e5020cf8b2a38f63b937746c0fb
    name: ontopic-studio
    type: application
    urls:
    - https://ontopic-vkg.github.io/ontopic-helm/ontopic-studio-0.1.0.tgz
    version: 0.1.0
generated: "2024-06-18T16:33:23.044289965+02:00"
