{{- range $name, $values := .Values.services }}
{{- with $values }}
---

{{- if and .service .ingress -}}
{{- $fullName := printf "%s-%s" (include "ontopic-studio.name" $) .service.name -}}
{{- $svcPort := .service.port -}}
{{- if and $.Values.ingress.className (not (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey $.Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set $.Values.ingress.annotations "kubernetes.io/ingress.class" .ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "ontopic-studio.labels" $ | nindent 4 }}
  {{- $annotations :=   $.Values.ingress.annotations | default .ingress.annotations }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $.Values.ingress.className (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $.Values.ingress.className | default .ingress.className }}
  {{- end }}
  {{- if or $.Values.ingress.tls .ingress.tls }}
  tls:
    {{- if .ingress.tls }}
    {{- range .ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
    {{- end }}
    {{- if $.Values.ingress.tls}}
    - hosts:
        - {{ $.Values.ingress.host | quote }}
      secretName: {{ $.Values.ingress.secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .ingress.hosts }}
    - host: {{ $.Values.ingress.host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
